obstacle_range: 2.0
raytrace_range: 2.75
footprint: [[-10,6], [10,6], [10,-14], [-10,-14]]
#robot_radius: 0.20
inflation_radius: 0.50

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: camera_depth_frame, data_type: PointCloud, topic: /camera/depth/points/PointCloud2, marking: true, clearing: true}
