obstacle_range: 2.0
raytrace_range: 2.75
footprint: [[-0.010,0.006], [0.010,0.006], [0.010,-0.014], [-0.010,-0.014]]
#robot_radius: 0.20
inflation_radius: 0.5

observation_sources: laser_scan_sensor
laser_scan_sensor: {data_type: LaserScan, topic: scan, marking: true, clearing: true}


#observation_sources: point_cloud_sensor
#point_cloud_sensor: {sensor_frame: camera_depth_frame, data_type: PointCloud, topic: /camera/depth/points/PointCloud2, marking: true, clearing: true}
